from native_tags.decorators import function
import cmath

acos = function(cmath.acos)
acosh = function(cmath.acosh)
asin = function(cmath.asin)
asinh = function(cmath.asinh)
atan = function(cmath.atan)
atanh = function(cmath.atanh)
cos = function(cmath.cos)
cosh = function(cmath.cosh)
e = function(cmath.e)
exp = function(cmath.exp)
isinf = function(cmath.isinf)
isnan = function(cmath.isnan)
log = function(cmath.log)
log10 = function(cmath.log10)
phase = function(cmath.phase)
pi = function(cmath.pi)
polar = function(cmath.polar)
rect = function(cmath.rect)
sin = function(cmath.sin)
sinh = function(cmath.sinh)
sqrt = function(cmath.sqrt)
tan = function(cmath.tan)
tanh = function(cmath.tanh)

