import math

from native_tags.decorators import function


acos = function(math.acos)
acosh = function(math.acosh)
asin = function(math.asin)
asinh = function(math.asinh)
atan = function(math.atan)
atan2 = function(math.atan2)
atanh = function(math.atanh)
ceil = function(math.ceil)
copysign = function(math.copysign)
cos = function(math.cos)
cosh = function(math.cosh)
degrees = function(math.degrees)
e = function(math.e)
exp = function(math.exp)
fabs = function(math.fabs)
factorial = function(math.factorial)
floor = function(math.floor)
fmod = function(math.fmod)
frexp = function(math.frexp)
fsum = function(math.fsum)
hypot = function(math.hypot)
isinf = function(math.isinf)
isnan = function(math.isnan)
ldexp = function(math.ldexp)
log = function(math.log)
log10 = function(math.log10)
log1p = function(math.log1p)
modf = function(math.modf)
pi = function(math.pi)
pow = function(math.pow)
radians = function(math.radians)
sin = function(math.sin)
sinh = function(math.sinh)
sqrt = function(math.sqrt)
tan = function(math.tan)
tanh = function(math.tanh)
trunc = function(math.trunc)
